### ISSUE TITLE
TODO on IDP

### ISSUE THREAD

**Issue by jaxoncreed** [inrupt/solid-idp#5]
# Things that must be done on the solid idp

- [ ] Create a script to generate keystore.json
- [ ] Figure out why keystore.json isn't able to be found on certain machines
- [ ] Create a custom UI
- [ ] Redis Account implementation
- [ ] Document setup in README
- [ ] Integrate standard IDP test
- [ ] Write webId specific tests
- [ ] Redis configuration
- [x] Translate the prefix to all urls
- [ ] Address errors on startup
